-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "favoriteCount" SET DEFAULT 0,
ALTER COLUMN "images" DROP NOT NULL,
ALTER COLUMN "images" SET DATA TYPE TEXT,
ALTER COLUMN "tags" DROP NOT NULL,
ALTER COLUMN "tags" SET DATA TYPE TEXT;
